name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  ruff_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.2
    - name: Install Poetry and dependencies
      run: |
        pip install poetry
        poetry install
    - name: Check formatting with Ruff
      run: poetry run ruff format --check .

  ruff_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.2
    - name: Install Poetry and dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run Ruff linter
      run: poetry run ruff check .

  build:
    runs-on: ubuntu-latest
    needs: [ruff_format, ruff_lint]  # Only build if these jobs pass
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.2
    - name: Install Poetry and dependencies
      run: |
        pip install poetry
        poetry install
    - name: Build the package
      run: poetry build
    - name: Upload wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: python-training-wheel
        path: dist/*.whl
